export function buildAgentRulesMarkdown() {
  return [
    "# VibeFoundry Agent Rules",
    "",
    "## 资产查找",
    "",
    "- 开始生成新组件、接口或产品方案前，先查本次 `distill` 输出的集中资产包目录。",
    "- 新增 UI 时优先复用已有 tokens，并检查 `tokens.json` 和 `component-catalog.json`。",
    "- 新增后端能力前优先检查 `service-catalog.json` 和 `business-patterns.md`。",
    "",
    "## 工程约束",
    "",
    "- 新增组件时优先复用已有组件结构和 tokens。",
    "- 新增后端能力时保留原 service 的输入、输出、依赖和安全约束。",
    "- 登录/注册/权限相关实现必须保留凭证校验、会话处理、频率限制和越权风险检查。",
    "",
    "## 产品与文化资产",
    "",
    "- 产品设计资产可作为命名、信息架构、交互和叙事参考。",
    "- 文化隐喻资产只能作为设计参考，不保存大段版权原文。",
    "- 使用隐喻资产时必须保留来源引用和适用边界。",
    "",
    "## 验证",
    "",
    "- 修改 VibeFoundry 后运行 `npm test` 和 `npm run build`。",
    "- 修改 CLI 输出后用 `node dist/cli.js distill <fixture-project>` 做端到端验证。",
    "",
  ].join("\n");
}
